### PR TITLE
MSC - AI, Sem - 2, Modern Algorithm Design (MAD) subject added

### PR DESCRIPTION
**Pull request by Viddesh1**
Hi @tusuii ,

I am trying to create a branch for MAD subject. Kindly review PR. Thanks!
Let me know if there is any issue.

Thanks!
Viddesh

### CODE REVIEW

**Comment by tusuii** [comment]
Thanks for adding a subject @Viddesh1 I hope There will more such PR's

**Comment by tusuii** [comment]
Thanks for your take @Viddesh1 , But i want to know why some files are deleted from AIP practicals, please check you have done it correctly

**Comment by Viddesh1** [comment]
Thanks for reviewing.

The reason why I have deleted the few files is because when I created a branch in vscode git bash terminal using below command:-
 ```
git checkout -b MAD
```

It created a new branch in my local machine with targeting "MAD" branch. But vscode was still displaying me the same files from branch name of "main" with all the files in the main branch.

As a result I deleted the files.

**Comment by Viddesh1** [comment]
Hi @tusuii ,

What is the status of this pull request?

**Comment by Viddesh1** [comment]
Hi @tusuii ,

Understood, I will check from my side.

Thanks!
Viddesh

**Pull request closed without merging**
